### ISSUE TITLE
Unfinished release of v6.3.0

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1828]
I am in the middle of releasing v6.3.0, but have to leave for a family event now. 

Most files should be available on SF already and Python wheels are uploaded as well. The docs are missing though. 

I’ll continue the work in about 10 hours.

**Comment by jowr** [comment]
Done - even javascript works again...

**Comment by ibell** [comment]
Awesome! Thanks!

**Comment by henningjp** [comment]
Yes! Thank you!
The Mathcad 15 binaries are finally back and the doc pages are updating again!  One niggling thing is that the new IF97 page is still not getting copied (error 403).  It's in the Dev docs, but not the release docs.

**Comment by jowr** [comment]
Which page? could you post a link?

**Comment by henningjp** [comment]
Main menu
Fluid Properties
IF97 Steam/Water Properties

Issue #1762 (Reopen?)

**Comment by ibell** [comment]
That file (and seemingly only that file) is cursed :(

The link from the homepage is also broken, FWIW

**Comment by henningjp** [comment]
Does the release process copy the html from the \dev directories, or rebuild them?  This is the only file name with numerals in it except for the change log pages.  I’m reaching.  Something is different that we’re not seeing.

**Comment by henningjp** [comment]
Uh, there’s a slash in it too...”Steam/Water”.  Is that hosing up the copy from dev?

**Comment by ibell** [comment]
Almost certainly you've found the problem.  I never use slashes in file
names because it can cause all kinds of havoc.  Can you rename that file?
And maybe Jorrit can pull the file from the subfolder generated in the
server as a quick fix?

**Comment by henningjp** [comment]
Sorry.  Afraid that's not it.  The Title has a slash in it, but the file name is just IF97.rst >> IF97.html.

When I created it, I basically took compressibles.rst and used it as a template.  I don't think I left anything behind.  Again, it works perfectly under www.coolprop.org/dev/.

**Comment by jowr** [comment]
Thank you for checking the docs! 

I have had a look at the release logs and there is nothing fishy there. Additionally, the latest nightly build that finished a few hours ago contains that file. What a mess!

To answer your earlier question: The docs are built from scratch for a release, but so does the first nightly build after a release. Nothing gets copied during a releaseeverything is built anew, performing a release also empties the folder for custom builds (unstable) and the ordinary CI folder (binaries) as well as the "release" folder itself.

I am going to have a closer look.

**Comment by jowr** [comment]
Here is what I found out so far:
 - The file is on the server
 - The error is actually a 403 error and not a 404 error
 - The above indicates that there is a permisson problem and not a file system problem

**Comment by jowr** [comment]
Done, see 9142a13 .

**Comment by spinnau** [comment]
Thanks for all the work on that release.

The files for the new extensions for LibreOffice are still missing on sourceforge. I have built the extension for the new v6.3.0 release and successfully tested it on Linux and Windows.

[CoolProp_LibreOffice_extension_v6.3.0.zip](https://github.com/CoolProp/CoolProp/files/3251265/CoolProp_LibreOffice_extension_v6.3.0.zip)

@jowr could you please upload the files from the attached zip-archive (.oxt extension and .ods example spreadsheet) to sourceforge? The docs already points to that link:
http://sourceforge.net/projects/coolprop/files/CoolProp/6.3.0/LibreOffice
