### ISSUE TITLE
Python 3.8 : Error in import

### ISSUE THREAD

**Issue by frisbee-w** [CoolProp/CoolProp#1876]
### Prerequisites

Checked.
    * Not reported in [CoolProp User Group](https://goo.gl/Pa7FBT)
    * Similar to #1872
    * Checked with the latest release 6.3.0 from [PyPI](https://pypi.org/project/CoolProp) and [development version](http://www.coolprop.org/dev) 6.3.1 (as suggested in https://github.com/CoolProp/CoolProp/issues/1872#issuecomment-560970428)

### Description

Hi,

I've tried installing the development build. It gets installed, but when importing the module, get the following.
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user0/.local/lib/python3.8/site-packages/CoolProp/__init__.py", line 22, in <module>
    __fluids__ = CoolProp.get_global_param_string('fluids_list').split(',')
  File "CoolProp.pyx", line 287, in CoolProp.CoolProp.get_global_param_string
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found
```

### Steps to Reproduce

1. Install CoolProp from PyPI or the development server  
2. Import the module in Python 3.8
```python
import CoolProp.CoolProp as CP
```

**Expected behavior:** Successful import

**Actual behavior:** Error

### Versions

**CoolProp Version:** 6.3.0 or 6.3.1  
**Operating System and Version:** Arch Linux
**Access Method:** Python 3.8    

### Additional Information

None

**Comment by frisbee-w** [comment]
Works with the build from GitHub sources.
Closing the issue.

**Comment by ibell** [comment]
Actually, I think this is abug,

**Comment by notmyrealhandle** [comment]
FWIW unsurprisingly this issues also exists for python 3.8.1 and pypi CoolProp 6.3.0.  

Building CoolProp 6.3.1.dev0 from (github) source does resolve the issue for me.  

I'm not sure its related but If it helps, I found [this](https://github.com/cython/cython/issues/2819) on the cython github issues site - perhaps when cython 3 is released there will be a change.

A few extraneous details
```
(p381.mkl) [160] $ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(p381.mkl) [161] $ python --version
Python 3.8.1
(p381.mkl) [162] $ pip list | grep Cython
Cython                   0.29.14            
```

**Comment by SpaceSapien** [comment]
I also have this problem with Python 3.8.0. When importing CoolProp the __init__.py errors:

```
    from CoolProp import CoolProp
/usr/local/lib/python3.8/site-packages/CoolProp/__init__.py:22: in <module>
    __fluids__ = CoolProp.get_global_param_string('fluids_list').split(',')
CoolProp.pyx:277: in CoolProp.CoolProp.get_global_param_string
    ???
stringsource:15: in string.from_py.__pyx_convert_string_from_py_std__in_string
    ???
E   TypeError: expected bytes, str found
```

`__fluids__ = CoolProp.get_global_param_string('fluids_list').split(',')`

I found a fix was to use byte strings. 

`CoolProp.get_global_param_string(b'fluids_list').split(b',')`

**Comment by ibell** [comment]
I am pretty sure I fixed this in the source, so I recommend you build from
the development server to check -- point 3:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation

**Comment by dailyllama** [comment]
I installed via development server as per your link but I still get an error; the fix SpaceSapien suggested includes byte string in the split.

import CoolProp.CoolProp as CP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/CoolProp/__init__.py", line 22, in <module>
    __fluids__ = CoolProp.get_global_param_string(b'fluids_list').split(',')
TypeError: a bytes-like object is required, not 'str'

**Comment by SpaceSapien** [comment]
Yes, I can verify that the split needed the byte string as well for a
successful import.

**Comment by ibell** [comment]
Can someone in this thread please submit a pull request fixing this issue?

**Comment by bryanwweber** [comment]
I'm the author of #1832 and I think this issue is a related and/or a duplicate of that one. Unfortunately, I haven't been able to investigate further.

**Comment by ibell** [comment]
I think finally that if you install the most recent versions of both Cython
(from pip) and CoolProp (from source), then everything should "just work".
Famous last words...  It worked for me at least...

**Comment by bryanwweber** [comment]
Thanks @ibell I had a chance to try the nightly Python build today, and I got the following error on macOS:
```
$ MACOSX_DEPLOYMENT_TARGET=10.14 python -m pip install --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp
Looking in links: http://www.coolprop.dreamhosters.com/binaries/Python/
Collecting CoolProp
  Using cached https://coolprop.dreamhosters.com/binaries/Python/CoolProp-6.3.1.dev0.tar.gz (12.9 MB)
Installing collected packages: CoolProp
    Running setup.py install for CoolProp ... done
Successfully installed CoolProp-6.3.1.dev0
$ python
Python 3.8.1 (default, Jan 24 2020, 13:10:10)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoolProp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bryan/.pyenv/versions/thermostate/lib/python3.8/site-packages/CoolProp/__init__.py", line 22, in <module>
    __fluids__ = CoolProp.get_global_param_string(b'fluids_list').split(',')
TypeError: a bytes-like object is required, not 'str'
```
I noticed that you reverted the change in #1896 that was supposed to fix this, but it seems it might still be required? Thank you!

**Comment by ibell** [comment]
You'll need to build from source to test this unfortunately.  The build system is a bit broken currently

**Comment by bryanwweber** [comment]
Ok thanks, I'll try that!

**Comment by jowr** [comment]
I guess this is fixed with 6.4.0

**Comment by bryanwweber** [comment]
@jowr I don't think this is fixed yet, I still get the `TypeError` with Python 3.8 compiling the `master` branch: https://github.com/bryanwweber/thermostate/pull/27/checks?check_run_id=686998963#step:11:46

**Comment by ibell** [comment]
I am using the binary wheels for 6.4.0 in python 3.8, no problems for me.
Can you please confirm that this persists after a clean build of the
environment?

**Comment by ibell** [comment]
Have you tried to build the wheel locally with bdist_whl followed by
install from the wheel?

**Comment by bryanwweber** [comment]
@ibell Sorry, that was my mistake. It pulled the 6.3.0 wheel because `master` is 6.4.0 and my version spec was `>=6.3.0,<6.4`, so it didn't install the wheel I built. All seems to be fixed now, thanks for the quick reply!

**Comment by ibell** [comment]
Great, thanks! Thanks for the update
