### ISSUE TITLE
Warnings for format_as when compiling with fmtlib version 10.0.0

### ISSUE THREAD

**Issue by friederikeboehm** [CoolProp/CoolProp#2290]
### Description

When compiling the Mathematica wrapper with latest master branch (43f1e96ce2e789d590b0c568f5fa7b513273276b), I get tons of warnings like this: 
```
 In file included from user\CoolProp\src\Backends/Cubics/CubicsLibrary.h:8,
                 from user\CoolProp\src\Backends/Cubics/CubicBackend.h:20,
                 from user\CoolProp\src\AbstractState.cpp:17:
user/CoolProp/include/CoolPropFluid.h:569:72: warning: optimization attribute on 'int CoolProp::format_as(CoolProp::ViscosityDiluteVariables::ViscosityDiluteType)' 
follows definition but the attribute doesn't match [-Wattributes]
 static int format_as(ViscosityDiluteVariables::ViscosityDiluteType type) {
                                                                        ^
In file included from user/CoolProp/include/CachedElement.h:12,
                 from user/CoolProp/include/AbstractState.h:11,
                 from user\CoolProp\src\AbstractState.cpp:14:
user/CoolProp/include/DataStructures.h:502:12: note: previous definition of 'int CoolProp::format_as(CoolProp::backend_families)' was here
 static int format_as(backend_families family) {
            ^~~~~~~~~
```
The resulting dll seems to work just fine.
I have tracked the origin back to PR #2252, before that I only had similiar errors for Solvers, which I could not find, when they first appeared.
When compiling with the old version of fmtlib (4.1) I get no warnings (except for the Solver ones) and dll is also working.

### Steps to Reproduce
Compile wrapper according to http://www.coolprop.org/coolprop/wrappers/Mathematica/index.html (with toolchain B)

**Expected behavior:** no warnings/errors, working dll

**Actual behavior:** many warnings, no errors, working dll

### Versions

**CoolProp Version:**  master branch (43f1e96ce2e789d590b0c568f5fa7b513273276b)
**Operating System and Version:** Win10
**Access Method:** Mathematica

**Comment by ibell** [comment]
I fixed this in development, please build from git sources

**Comment by friederikeboehm** [comment]
Seems like I missed the last two commits on master, still have the same problem with master at c4108e5a, same error messages (just changed from `static` to `inline`, should 3cab04a6 have fixed my problem?):
```
In file included from user\CoolProp\src\Backends/Cubics/CubicsLibrary.h:8,
                 from user\CoolProp\src\Backends/Cubics/CubicBackend.h:20,
                 from user\CoolProp\src\AbstractState.cpp:17:
user/CoolProp/include/CoolPropFluid.h:569:72: warning: optimization attribute on 'int CoolProp::format_as(CoolProp::ViscosityDiluteVariables::ViscosityDiluteType)' 
follows definition but the attribute doesn't match [-Wattributes]
 inline int format_as(ViscosityDiluteVariables::ViscosityDiluteType type) {
                                                                        ^
In file included from user/CoolProp/include/CachedElement.h:12,
                 from user/CoolProp/include/AbstractState.h:11,
                 from user\CoolProp\src\AbstractState.cpp:14:
user/CoolProp/include/DataStructures.h:502:12: note: previous definition of 'int CoolProp::format_as(CoolProp::backend_families)' was here
 inline int format_as(backend_families family) {
            ^~~~~~~~~
```

**Comment by ibell** [comment]
I just recompiled and I didn't see any of these errors, are you sure you are building from the current master?

**Comment by friederikeboehm** [comment]
Yes, I was using the current master. After successfully compiling on a different computer I first thought this has something to do with a newer Mathematica version (13.3), but after upgrading on the other computer (from 13.1 to 13.3) i figured out its the gcc version. For some reason (probably some course I took) I had two versions installed and the old version was first found on path or whatever... Sorry for bothering you.
