### ISSUE TITLE
TTSE/Bicubic exception with SES36

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#666]
If I try to call `AbstractState::factory("TTSE&HEOS", "SES36")` or `AbstractState::factory("BICUBIC&HEOS", "SES36")`, it raises an exception whose message is "For now, we don't support p below ptriple". I'm using the latest version (5.1.1dev) of the C++ library (don't ask for git revision, no gitrevision.h was created so I hardcoded a dummy value to succeed in building the static library).

**Comment by Astrinus** [comment]
I tried to use R245fa for testing purposes, since on the website is cited as an example. Tables build fine, but then several problems near the two-phase zone arise: no construction, or exception when calculating derivatives apart from dT/dP or dP/dT along the saturation line.

**Comment by ibell** [comment]
Can you please provide a working example for R245fa?  If you are near
saturation, there is a known bug with P-T inputs:
https://github.com/CoolProp/CoolProp/issues/629

**Comment by Astrinus** [comment]
Yes, I'm near the saturation. How would you calculate derivatives along the saturation curve if you stay away from it? ;-)
Anyway, what about SES36?
I thought that using interpolating tables would result in smoother function, because all MatLab solvers get excessively slow when approaching an equilibrium position, and almost all exhibit numerical instability in the neighbourhood of the equilibrium, except ode45: this converges (but pressure can vary by 4 Pa and still it is considered the same equilibrium) but is extremely slow all the time.

**Comment by ibell** [comment]
The tables are in two parts - one for single-phase and one for two-phase.
Are you using PT inputs?  You might want to use TTSE instead of Bicubic, it
has better behavior around saturation until I fix the BICUBIC around
saturation bug.

Again, please provide working code demonstrating your problem.

**Comment by ibell** [comment]
BICUBIC should yield smooth first derivatives in variables with either PT or PH inputs.  If you want things like c_p, it is possible you might see some steps.  Can you show some examples demonstrating the "relatively big steps" as you mention?

**Comment by ibell** [comment]
You should be able to generate tables for SES36 now, I fixed a couple of bugs.

**Comment by Astrinus** [comment]
First, I apologize for not answering you yesterday (I had to stay away from PC).
0) For SES36 I now get an error ("Step is small but not solved to tolerance") when trying to build tables (from C++, latest version).
1) I dug into the BicubicBackend code and discovered that saturation derivatives of mass based quantities are currently unsupported. For this project I need d(Hmass)/d(P)|sigma, d(Dmass)/d(P)|sigma, d(Dmass)/d(Hmass)|P, d(Dmass)/d(P)|Hmass. I'll make a workaround from the molar ones.
2) I've found a bug (MATLAB and CoolProp wrapper nightly release, but present also in 5.1.0): the entropy on the saturation line gives the value of the enthalpy for BicubicBackend (see below).
3) With the nightly build most of the *derivative issues* were overcome. For the "relatively big step", perhaps I haven't emphasized the word "relatively" enough: these are very small if we take relative variation of output, O(10^(-6)) when input changes by O(10^(-7.5)). Still an high sensitivity, but I think it is acceptable for the vast majority of CoolProp use cases. The point I'm referring is around 4.57 bar and 88.26 °C, but I'm afraid I cannot be more precise because exact data has been discarded and at the moment there isn't enough time to run the simulation again until next week or more :-(

Example code:

    >> as=[CoolProp.AbstractState.factory('HEOS','R245fa');CoolProp.AbstractState.factory('BICUBIC&HEOS','R245fa')];
    >> as(1).update(CoolProp.PQ_INPUTS, 350000, 1)
    >> as(2).update(CoolProp.PQ_INPUTS, 350000, 1)
    >> as(1).hmass()
        ans = 4.4308e+05
    >> as(2).hmass()
        ans = 4.4308e+05
    >> as(1).smass()
        ans = 1.7685e+03
    >> as(2).smass()   % Bicubic backend returns enthalpy instead of entropy on the saturation line!
        ans = 4.4308e+05

**Comment by ibell** [comment]
0) operating system, platform, compiler?
1) #673
2) #672
3) Yes, that is basically at the limits of interpolation methods I am afraid.  If you can find a good test case, let me know

**Comment by ibell** [comment]
0) I forgot to push the thing that might fix the SES problem, can you try again now?
2) Fixed

**Comment by Astrinus** [comment]
0) Win 8.1, Intel x64 (i5-4200U), Visual Studio 2013 Win64. I'll check by an hour, sorry.
1+2) Thanks
3) Ok.

**Comment by Astrinus** [comment]
No change, it raises the following error:

    Loading table: C:\Users\my_username/.CoolProp/Tables/HelmholtzEOSBackend(SES36[1.000
0000000])/single_phase_logph.bin.z
    Step is small but not solved to tolerance

The table that CoolProp is trying to load doesn't exist on my filesystem. Shouldn't it generate on the first call like R245fa?

**Comment by ibell** [comment]
It first tries to load the table if it exists, then falls back to
generating the table.

**Comment by ibell** [comment]
I'll have another go this evening.

**Comment by ibell** [comment]
1) fixed

**Comment by ibell** [comment]
0) Works for me.  Can you provide a non-working minimal example please?

**Comment by Astrinus** [comment]
You can found the .exe and the .cpp at www.stealter.altervista.org/CPNW.zip
It builds tables fine for Water and R245fa but not for SES36.
Please tell me when you have downloaded the file so I can remove the link from this message.

**Comment by ibell** [comment]
I got it - how did you compile this code?  Looks like it is c++11?

**Comment by Astrinus** [comment]
Yes, it is C++11 (I like it a lot over C++0x). I used Visual C++ 2013 Win64 compiler. The solution tree was 26 MB zipped so I didn't include for now. If you need it I'll post as well.

**Comment by ibell** [comment]
Well, let me see if I can compile it and see the same behavior as you.  I
can use SES36 just fine in VS2012 x64, so I don't see why there would be a
difference.  Perhaps something weird with C++11?

**Comment by Astrinus** [comment]
Ok, you can found the complete tree at www.stealter.altervista.org/ConsoleApplication1.zip
You need to adjust paths to headers and static library (which are not included). Let me know if you need these too.
What is strange is that it works, for example, for R245fa and Water, but not for SES36. So I think the problem is not C++11.

**Comment by ibell** [comment]
But for me (not using C++11) in VS2012x64, it works just fine to build.
Which makes me think it is a c++11 issue

**Comment by Astrinus** [comment]
Does my VS solution builds fine?

**Comment by ibell** [comment]
No, it seems to have some external dependencies.

**Comment by ibell** [comment]
Cannot replicate.  I took the below code and created a visual studio project using cmake doing something like

`` cmake ../.. -G "Visual Studio 12 2013 Win64" -DCOOLPROP_MY_MAIN=main.cpp ``

from a directory two below the folder that contains CMakeLists.txt.

Builds, runs, just fine.  I wonder if it has something to do with your use of CLR and/or PCH.  Recommend you do not use either for testing purposes.

main.cpp:
``` C++

// ConsoleApplication1.cpp : file di progetto principale.

#include <memory>
#include <string>
#include <stdexcept>
#include "CoolProp.h"
#include "AbstractState.h"
#include "CoolPropTools.h"

int main()
{
	std::string fluid, backend;
	std::cout << "Insert fluid name: ";
	std::cin >> fluid;
	std::cout << "Insert backend name: ";
	std::cin >> backend;

	std::shared_ptr<CoolProp::AbstractState> CP;
	try {
		CP.reset(CoolProp::AbstractState::factory(strstrip(backend), strstrip(fluid)));
	}
	catch (const std::exception & e) {
		std::cout << "\nException: " << e.what() << std::endl;
		return 1;
	}

	CP->update(CoolProp::input_pairs::HmassP_INPUTS, 500000, 300000);
	std::cout << "\nTemperature: " << CP->T() << " K\n" << "Entropy: " << CP->smass() << " J/kg/K" << std::endl;

	return 0;
}

```
